# Generated by Django 3.2.3 on 2021-09-09 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0004_deliverytype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=150, null=True, verbose_name='Location latitude')),
                ('longitude', models.CharField(blank=True, max_length=150, null=True, verbose_name='Location longitude')),
                ('status', models.BooleanField(choices=[(True, 'Faol'), (False, 'Nofaol')], default=True, verbose_name='Holati')),
                ('delivery_current_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverycurrentdistrict', to='data.district')),
                ('delivery_current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverycurrentlocation', to='data.province')),
                ('delivery_finish_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryfinishdistrict', to='data.district')),
                ('delivery_finish_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryfinishlocation', to='data.province')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.deliverytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
