# Generated by Django 3.2.3 on 2021-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('language', models.CharField(choices=[('oz', "O'zbek"), ('uz', 'Узбек'), ('ru', 'Руский'), ('en', 'Ingliz')], max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('customer', 'Mijoz'), ('drive', 'Haydovchi')], max_length=10, null=True)),
                ('device', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('account', models.PositiveIntegerField(default=0)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
