# Generated by Django 3.2.3 on 2021-08-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('customer', 'Mijoz'), ('driver', 'Haydovchi')], max_length=10, null=True),
        ),
    ]
