# Generated by Django 3.2.3 on 2021-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.IntegerField(default=0),
        ),
    ]
