# Generated by Django 3.2.3 on 2021-09-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20210828_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsmodel',
            options={'verbose_name': 'Sms', 'verbose_name_plural': 'Smslar'},
        ),
    ]
