# Generated by Django 3.2.3 on 2021-09-04 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0003_auto_20210901_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers_count', models.IntegerField()),
                ('phone_number', models.CharField(max_length=12)),
                ('latitude', models.CharField(blank=True, max_length=150, null=True, verbose_name='Location latitude')),
                ('longitude', models.CharField(blank=True, max_length=150, null=True, verbose_name='Location longitude')),
                ('sex', models.CharField(choices=[('man', 'Erkak'), ('woman', 'Ayol')], max_length=5, verbose_name='Jinsi')),
                ('status', models.BooleanField(choices=[(True, 'Faol'), (False, 'Nofaol')], default=True, verbose_name='Holati')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.automobile')),
                ('customer_current_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_current_district', to='data.district')),
                ('customer_current_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_current_province', to='data.province')),
                ('customer_finish_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_finish_district', to='data.district')),
                ('customer_finish_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_finish_province', to='data.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Yulovchi e'loni",
                'verbose_name_plural': "Yulovchilar e'lonlari",
            },
        ),
    ]
