# Generated by Django 3.2.3 on 2021-09-09 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_deliverytype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.automobile', verbose_name='Avtomobil'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_current_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_current_district', to='data.district', verbose_name='Turgan tuman'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_current_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_current_province', to='data.province', verbose_name='Turgan viloyat'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_finish_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_finish_district', to='data.district', verbose_name='Boradigan tuman'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_finish_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_finish_province', to='data.province', verbose_name='Boradigan viloyat'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passengers_count',
            field=models.IntegerField(verbose_name="Yo'lovchi soni"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
