# Generated by Django 3.2.3 on 2021-08-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oz', models.CharField(max_length=50, unique=True)),
                ('uz', models.CharField(max_length=50, unique=True)),
                ('ru', models.CharField(max_length=50, unique=True)),
                ('en', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('1', '1-TOIFA'), ('2', '2-TOIFA'), ('3', '3-TOIFA'), ('4', '4-TOIFA')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oz', models.CharField(max_length=50, unique=True)),
                ('uz', models.CharField(max_length=50, unique=True)),
                ('ru', models.CharField(max_length=50, unique=True)),
                ('en', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oz', models.CharField(max_length=50, unique=True)),
                ('uz', models.CharField(max_length=50, unique=True)),
                ('ru', models.CharField(max_length=50, unique=True)),
                ('en', models.CharField(max_length=50, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.province')),
            ],
        ),
        migrations.CreateModel(
            name='Deriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_deriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aderiction', to='data.province')),
                ('b_deriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bderiction', to='data.province')),
                ('c_deriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cderiction', to='data.province')),
            ],
        ),
    ]
