# Generated by Django 3.2.3 on 2021-08-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='category',
            field=models.CharField(choices=[('1', '1-TOIFA'), ('2', '2-TOIFA'), ('3', '3-TOIFA'), ('4', '4-TOIFA')], max_length=2, verbose_name='Kategorya'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='en',
            field=models.CharField(max_length=50, unique=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='oz',
            field=models.CharField(max_length=50, unique=True, verbose_name="O'zbek"),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='ru',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rus'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='uz',
            field=models.CharField(max_length=50, unique=True, verbose_name='Узбек'),
        ),
        migrations.AlterField(
            model_name='deriction',
            name='a_deriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aderiction', to='data.province', verbose_name='A manzil'),
        ),
        migrations.AlterField(
            model_name='deriction',
            name='b_deriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bderiction', to='data.province', verbose_name='B manzil'),
        ),
        migrations.AlterField(
            model_name='deriction',
            name='c_deriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cderiction', to='data.province', verbose_name='C manzil'),
        ),
        migrations.AlterField(
            model_name='district',
            name='en',
            field=models.CharField(max_length=50, unique=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='district',
            name='oz',
            field=models.CharField(max_length=50, unique=True, verbose_name="O'zbek"),
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.province', verbose_name='Tegishli viloyat'),
        ),
        migrations.AlterField(
            model_name='district',
            name='ru',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rus'),
        ),
        migrations.AlterField(
            model_name='district',
            name='uz',
            field=models.CharField(max_length=50, unique=True, verbose_name='Узбек'),
        ),
        migrations.AlterField(
            model_name='province',
            name='en',
            field=models.CharField(max_length=50, unique=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='province',
            name='oz',
            field=models.CharField(max_length=50, unique=True, verbose_name="O'zbek"),
        ),
        migrations.AlterField(
            model_name='province',
            name='ru',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rus'),
        ),
        migrations.AlterField(
            model_name='province',
            name='uz',
            field=models.CharField(max_length=50, unique=True, verbose_name='Узбек'),
        ),
    ]
