# Generated by Django 3.2.3 on 2021-09-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210830_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobile',
            options={'verbose_name': 'Avtomobil', 'verbose_name_plural': 'Avtomobillar'},
        ),
        migrations.AlterModelOptions(
            name='deriction',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
    ]
