# Generated by Django 3.2.3 on 2021-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210901_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oz', models.CharField(max_length=50, unique=True, verbose_name="O'zbek")),
                ('uz', models.CharField(max_length=50, unique=True, verbose_name='Узбек')),
                ('ru', models.CharField(max_length=50, unique=True, verbose_name='Rus')),
                ('en', models.CharField(max_length=50, unique=True, verbose_name='English')),
                ('order', models.IntegerField(unique=True, verbose_name="Saralash o'rni")),
            ],
        ),
    ]
