# Generated by Django 3.2.3 on 2021-09-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_deliverytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'verbose_name': 'Pochta turi', 'verbose_name_plural': 'Pochta turi'},
        ),
    ]
