# Generated by Django 3.2.3 on 2021-08-30 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20210830_1232'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercart',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.automobile', verbose_name='Avtomobil rusumi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='baggage',
            field=models.IntegerField(choices=[(0, "YO'Q"), (1, 'BOR')], verbose_name='Yuk'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cooling_system',
            field=models.IntegerField(choices=[(0, "YO'Q"), (1, 'BOR')], verbose_name='Sovutish tizimi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='deriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.deriction', verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='driver',
            name='district',
            field=models.ManyToManyField(to='data.District', verbose_name='Qatnov tumanlari'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fuel',
            field=models.CharField(choices=[('gaz', 'GAZ'), ('benzin', 'BENZIN')], max_length=6, verbose_name="Yoqilg'i turi"),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number_one',
            field=models.CharField(max_length=12, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number_two',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name="Qo'shimcha telefon raqam"),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sex',
            field=models.CharField(choices=[('man', 'Erkak'), ('woman', 'Ayol')], max_length=5, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentlocation', to='data.province', verbose_name='Hozirgi manzil'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='customer',
            field=models.ManyToManyField(related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Yulovchi'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='Pochta'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='delivery_user',
            field=models.ManyToManyField(related_name='delivery_user', to=settings.AUTH_USER_MODEL, verbose_name='Pochta'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Haydovchi'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='empty_count',
            field=models.IntegerField(verbose_name="Bo'sh joylar soni"),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='finish_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishlocation', to='data.province', verbose_name='Boradigan manzil'),
        ),
    ]
