# Generated by Django 3.2.3 on 2021-09-01 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20210830_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Haydovchi', 'verbose_name_plural': "Haydovchi e'loni"},
        ),
        migrations.AlterModelOptions(
            name='drivercart',
            options={'verbose_name': 'Qidiruv', 'verbose_name_plural': "Qidiruv e'loni"},
        ),
        migrations.AddField(
            model_name='driver',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drivercart',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
