# Generated by Django 3.2.3 on 2021-09-04 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0006_alter_drivercart_delivery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercart',
            name='delivery_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='delivery_user', to=settings.AUTH_USER_MODEL, verbose_name='Olingan pochta egasi'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='status',
            field=models.BooleanField(choices=[(True, 'Faol'), (False, 'Nofaol')], default=True, verbose_name='Holati'),
        ),
    ]
