# Generated by Django 3.2.3 on 2021-09-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_auto_20210904_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercart',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Narxi'),
        ),
    ]
