# Generated by Django 3.2.3 on 2021-09-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0008_drivercart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercart',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Narxi (narx kiritilmasa kelishilgan narx tanlanadi)'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_clean', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Tozalik Ball')),
                ('rating_talk', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Muomila Ball')),
                ('rating_time', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Vaqtida kelishi Ball')),
                ('comment', models.CharField(max_length=255, verbose_name='Izoh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Reyting',
                'verbose_name_plural': 'Reytinglar',
            },
        ),
    ]
