# Generated by Django 4.1.5 on 2023-01-16 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0010_alter_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercart',
            name='customer',
            field=models.ManyToManyField(related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Yulovchi'),
        ),
        migrations.AlterField(
            model_name='drivercart',
            name='delivery_user',
            field=models.ManyToManyField(related_name='delivery_user', to=settings.AUTH_USER_MODEL, verbose_name='Olingan pochta egasi'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_clean',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Tozalik Ball'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_talk',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Muomila Ball'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_time',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Vaqtida kelishi Ball'),
        ),
    ]
